dataset:
  SynthText:
    root_dir: I:\ML_DATASET\mnt\data
    train_num: 100000
    val_num: 3200
    test_num: 80
    img_height: 32
  trdg:
    root_dir: [F:\img\synth\out_1, F:\img\synth\out_2, F:\img\synth\out_3]

lexicon:
  blank: 91

crnn:
  imgH: 32
  nc: 1
  nh: 256
  nClass: 92
  backbone: vgg
  num_rnn: 1

train:
  epochs: 500
  lr: 0.0001
  batch_size: 32
  checkpoint:
